# language settings
[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }
language-servers = [
  "vscode-json-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsonc"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }
language-servers = [
  "vscode-json-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md"] }
auto-format = true
language-servers = ["markdown-oxide"]

[[language]]
name = "astro"
formatter = { command = "prettier", args = ["--parser", "astro"] }
auto-format = true
language-servers = ["astro-ls", "vscode-eslint-language-server"]

[[language]]
name = "svelte"
auto-format = true
language-servers = [
  "svelteserver",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true

# create workspace config for connections
# ref: https://github.com/joe-re/sql-language-server
[[language]]
name = "sql"
language-servers = ["sql-language-server"]

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "awk"
formatter = { command = "awk", timeout = 5, args = [
  "--file=/dev/stdin",
  "--pretty-print=/dev/stdout",
] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


[[language]]
name = "powershell"
scope = "source.ps1"
file-types = ["ps1", "psm1"]
roots = [".git"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = ["powershell-editor-services"]

[[language]]
name = "python"
formatter = { command = "black", arg = ["--line-length", "88", "--quiet", "-"] }
language-servers = ["pyright", "ruff"]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
auto-format = true
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle" }

[[language]]
name = "xml"
auto-format = true
formatter = { command = "xmllint", args = ["--format", "-"] }

# lsp settings

# yaml
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

# rust
[language-server.rust-analyzer.config.check]
command = "clippy"

# python
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff-lsp"
config = { settings = { args = ["--ignore", "E501"] } }

# powershell
[language-server.powershell-editor-services]
command = "pwsh"
args = [
  "-NoLogo",
  "-NoProfile",
  "-Command",
  "D:\\Document\\PowerShell\\Modules\\PowerShellEditorServices\\PowerShellEditorServices\\Start-EditorServices.ps1 -BundledModulesPath D:\\Document\\PowerShell\\Modules\\PowerShellEditorServices -SessionDetailsPath D:\\Document\\PowerShell\\Modules\\PowerShellEditorServices\\PowerShellEditorServices.sessions.json -LogPath D:\\Document\\PowerShell\\Modules\\PowerShellEditorServices\\PowerShellEditorServices.log -FeatureFlags @() -AdditionalModules @() -HostName helix -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal",
]

# latex
[language-server.texlab.config.texlab.build]
onSave = true

# sql
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
# config = { typescript = { tsdk = "/Users/user/.bun/install/global/node_modules/typescript/lib" }, environment = "node" } # Add config for typescipt

[language-server.vscode-json-language-server.config]
# provideFormatter = true
json = { keepLines = { enable = true } }

[language-server.tailwindcss-ls.config.userLanguages]
vue = "html"
"*.vue" = "html"

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "vue-language-server"
languages = ["vue"]
